(function(){'use strict';
 const el=id=>document.getElementById(id),select=el('method-mode');if(!select)return;
 const names={fixed:'Stop at layer 2',adaptive:'Check before continuing',cascade:'Small model, then larger model',training:'Compare trained weights',batch:'Process four messages together',quantization:'Float32 versus INT8'};
 const notes={fixed:'Same four-layer BERT: all four layers versus a fixed stop after layer 2. This illustrates the approach; it does not reproduce the Qwen layer-12 test.',adaptive:'The saved rule checks layer 2, then either returns a label or continues from that hidden state. Lower layers run once.',cascade:'A separate 4.37M BERT answers first. Scores between 0.05 and 0.95 fall back to an 11.1M BERT. This new pairing is an illustration, not the measured tiny-to-Qwen cascade. The cutoff is not validated for this pairing.',training:'Earlier shared-model weights versus the development-selected teacher-trained checkpoint. Both run all four layers. This compares existing trained models; it does not train in the browser.',batch:'Same model and messages, processed singly or in padded groups of four. All layers run. This measures an available queue, not live arrival latency.',quantization:'Same BERT classifier in float32 or with dynamic INT8 matrix weights. All layers run. This new BERT conversion is separate from the failed Qwen INT8 study.'};
 const labels={full:'All 4 layers',fixed2:'Stop at layer 2',adaptive:'Adaptive stop',cascade:'Tiny → larger BERT',trained:'Updated training',batch4:'Groups of four',int8:'INT8 weights'};
 const requested=new URLSearchParams(location.search).get('method');if(names[requested])select.value=requested;
 let worker=null,report=null;const status=el('method-status');
 function describe(){el('method-description').textContent=notes[select.value];history.replaceState(null,'','?method='+select.value);}
 function busy(value){for(const id of ['method-run','method-classify','method-mode','method-count','method-text'])el(id).disabled=value;el('method-stop').disabled=!value;}
 function resetWorker(){if(worker)worker.terminate();worker=null;}
 function cell(row,text,tag='td'){const e=document.createElement(tag);e.textContent=text;if(tag==='th')e.scope='row';row.appendChild(e);}
 function render(r){report=r;el('method-save').disabled=false;el('method-rows').replaceChildren();for(const s of r.summary){const tr=document.createElement('tr');cell(tr,labels[s.path],'th');cell(tr,s.correct===null?(s.prediction?'BLOCK':'SAFE'):s.correct+' / '+s.n);cell(tr,s.ms.toFixed(1)+' ms');cell(tr,s.meanBlocks.toFixed(2));cell(tr,String(s.changed));el('method-rows').appendChild(tr);}el('method-result').hidden=false;el('method-detail').textContent=r.kind==='benchmark'?r.summary.map(s=>labels[s.path]+': '+s.missedToxic+' toxic messages missed; '+s.falseBlocks+' false blocks; '+s.addedErrors+' new errors and '+s.correctedErrors+' corrections versus full depth.').join(' '):'Your message has no reference label, so accuracy is not scored.';el('method-time-note').textContent='Time is for '+r.summary[0].n+' message(s), averaged over '+r.passes+' pass(es). Setup for this action: '+(r.setupMs/1000).toFixed(2)+' s, excluded from inference time. Different-sized models’ block counts are not equal amounts of computation.';status.textContent='Finished. These are results measured on your device.';}
 function run(type){const text=el('method-text').value;if(type==='classify'&&(!text.trim()||text.length>10000)){status.textContent='Enter 1 to 10,000 characters.';return;}busy(true);status.textContent='Preparing the comparison...';el('method-save').disabled=true;el('method-result').hidden=true;report=null;if(!worker){worker=new Worker('scripts/method-demo-worker.js');worker.onmessage=({data:d})=>{if(d.type==='status')status.textContent=d.text;if(d.type==='complete'){render(d.report);busy(false);}if(d.type==='error'){status.textContent=d.text;busy(false);resetWorker();}};worker.onerror=e=>{status.textContent=e.message||'The browser could not run the model.';busy(false);resetWorker();};}worker.postMessage({type,mode:select.value,count:Number(el('method-count').value),text});}
 select.addEventListener('change',()=>{resetWorker();report=null;el('method-result').hidden=true;el('method-save').disabled=true;describe();status.textContent='Ready. Models load only when you run a comparison.';});
 el('method-run').onclick=()=>run('benchmark');el('method-classify').onclick=()=>run('classify');el('method-stop').onclick=()=>{resetWorker();busy(false);status.textContent='Stopped. No partial result is presented as complete.';};el('method-save').onclick=()=>{if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='skindeep-'+report.mode+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};describe();
})();
