"""Summarize bounded exploratory comparisons without replacing prior validation."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def read(name):return json.loads((ROOT/name).read_text(encoding='utf-8'))
def table(headers,rows):return ['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+['| '+' | '.join(map(str,r))+' |' for r in rows]

def main():
    required=[ROOT/f'results/chat-smoke-adaptation/{v}.json' for v in ['full','joint','distill','fixed12']]
    if not all(p.exists() for p in required):print('Waiting for all four adaptation results; no partial comparison published.');return
    h=read('results/chat-smoke-heads/result.json');s=read('results/chat-smoke-specialist/result.json')['splits']['evaluation'];b=read('results/chat-smoke-adaptation/initial-frozen-baseline.json');a={p.stem:read(p) for p in required}
    rows=[]
    for name,family,method in [('Linear readout','linear','fixed_24'),('Small neural readout','mlp','fixed_24'),('Separate SAFE/BLOCK thresholds','mlp','asymmetric'),('Checkpoint agreement','mlp','agreement'),('Learned gate, linear readout','linear','learned'),('Learned gate, neural readout','mlp','learned')]:
        m=h[family][method]['splits']['evaluation'];rows.append([name,m['correct'],m['missed_toxic'],m['false_block'],f'{100*m["projected_blocks_skipped"]:.2f}%'])
    for name,key in [('Tiny specialist','specialist'),('Specialist then Qwen','cascade'),('Older Qwen fallback reference (1,400 training labels)','full_qwen_reference')]:
        m=s[key];rows.append([name,m['correct'],m['missed_toxic'],m['false_block'],'0.00%' if key=='full_qwen_reference' else 'Different architecture'])
    lines=['# Trying eight approaches with small experiments','',
       '**Exploration, not validation.** These are 100 previously inspected ToxicChat messages, balanced to 50 toxic and 50 benign labels. Every candidate is reported. The sample helps choose follow-ups; it does not estimate natural chat prevalence or establish deployment reliability.','',
       '## Readouts, stopping rules and a specialist','',*table(['Method','Correct /100','Toxic missed /50','Benign blocked /50','Projected Qwen blocks skipped'],rows),'',
       'The two new full-depth readouts use 384 training messages. The specialist is a 4.37-million-parameter BERT trained on those same messages; its Qwen fallback is the older 1,400-message-trained classifier. That is an unequal-supervision fallback reference, not a controlled model-architecture ranking.','',
       'The neural learned gate adds one error and corrects three relative to its full-depth readout. It newly misses no toxic messages in these 50 positive examples, but the sample is too small for the earlier reliability tolerance. The specialist cascade adds two errors and corrects three, including one new toxic miss. Net accuracy cannot cancel those harms.','',
       'REVIEW is also tested. The neural readout accepts 64 messages and gets 56 right (87.5%), leaving 36 unresolved. It fails its development target of 95% accepted-answer accuracy. The linear rule sends all 100 to REVIEW because no eligible development threshold exists. Neither outcome counts unresolved requests as correct.','',
       '[All head/gate comparisons and completed timing](chat-smoke-heads.md), [specialist and cascade](chat-smoke-specialist.md). Feature-cache projections alone are not speedups.','']
    training=[];changes={};base={r['id']:r for r in b['predictions']['evaluation']}
    for name,v,d in [('Frozen starting readout, layer 24',None,'24'),('Task adaptation, full 24','full','24'),('Intermediate training losses, full 24','joint','24'),('Intermediate losses + distillation, full 24','distill','24'),('Frozen starting readout, layer 12',None,'12'),('Physically truncated 12 + adaptation','fixed12','12')]:
        m=b['metrics']['evaluation'][d] if v is None else a[v]['metrics']['evaluation'][d];training.append([name,m['correct'],m['missed_toxic'],m['false_block'],'Initial' if v is None else a[v]['selected_step']])
        if v:
            p=[r for r in a[v]['predictions'] if r['split']=='evaluation'];changes[v]={'added_errors':sum(base[r['id']]['heads'][d]['prediction']==r['label'] and r['heads'][d]['prediction']!=r['label'] for r in p),'corrected_errors':sum(base[r['id']]['heads'][d]['prediction']!=r['label'] and r['heads'][d]['prediction']==r['label'] for r in p),'additional_missed_toxic':sum(r['label']==1 and base[r['id']]['heads'][d]['prediction']==1 and r['heads'][d]['prediction']==0 for r in p)}
    runtime=read('results/chat-smoke-heads/runtime.json')
    f=runtime['paths']['full'];g=runtime['paths']['learned']
    lines+=['## Actual early-stop execution','',f'The full neural readout took {f["sum_seconds"]:.1f} seconds for 100 messages; the learned gate took {g["sum_seconds"]:.1f} seconds, a {100*runtime["relative_sum_time_saving"]:.1f}% reduction in summed request time. This is one warm paired pass, alternating path order, on one CPU with four threads and no concurrent model jobs. Original text preparation, readouts, gates and hooks are included; loading and training are excluded.','',
        'The gate stopped 32 messages at block 6, 11 at block 12, 17 at block 18, and carried 40 through all 24 blocks. Every executed block trace and prediction matched the recorded policy. The gate uses checkpoint scores and their changes to predict an error or whether more layers would help; it does not inspect an unavailable final-layer answer.','',
        '[Timing summary](../results/chat-smoke-heads/runtime.json), [all 200 timed calls](../results/chat-smoke-heads/runtime-records.json). This is measured computation saving on reused examples, not a verified equal-quality deployment speedup.','',
        '## Training the model, rather than only its readout','',
        'All four adapter recipes fit their initial linear heads on 384 messages, then take only 32 batches of four adapter updates: 128 message presentations. Checkpoints at steps 16 and 32 are selected on a 32-message development subset. This is a short-budget experiment, not a comparison of converged training methods. The original slower attempt and the prospective budget amendment are preserved.','']
    lines+=table(['Recipe','Correct /100','Toxic missed /50','Benign blocked /50','Selected step'],training)
    lines+=['',*table(['Recipe versus its initial readout','New errors','Corrected errors','New toxic misses'],[[k,v['added_errors'],v['corrected_errors'],v['additional_missed_toxic']] for k,v in changes.items()]),'',
       'Intermediate-loss and distillation rows above still use all 24 layers for the primary output. Their separate layer scores are diagnostic; they do not by themselves establish an adaptive stopping policy. The fixed-12 model actually contains twelve decoder blocks.','',
       'The distillation teacher is the selected task-adapted full model trained on the same labels. Its training-set logits are in-sample soft targets, not independent labels or proof that the teacher is stronger. Initial heads can already nearly fit this small training set, leaving little classification loss to drive useful adapter changes. Checkpoint selection excludes step 0; regressions against that initial readout remain visible.','',
       '[Adapter methods, every layer and artifacts](chat-smoke-adaptation.md).','',
       '## Maze and coordinate follow-ups','',
       '- A structured maze policy trained on the original 256 states still reaches 0/10 goals; forbidding wall collisions raises it to 2/10. Training on 4,992 states from the same training layouts raises this to 5/10, or 7/10 with the explicit legal-action mask. BFS reaches 10/10. More supervision and legal constraints help, but legal loops remain. [Maze details](maze-smoke.md).',
       '- A confidence-only coordinate rejection rule rejects both absent targets across two screenshot folds, with no rejected present targets. It still accepts one wrong coordinate. These are eight previously inspected examples of the same interface and repeated instructions, not a learned visual presence head or general absent-target validation. [Coordinate diagnostic](coordinate-abstention-smoke.md).','',
       '## What these tests can establish','',
       'A development split chooses each policy before that policy is evaluated; however, all examples were already inspected in the earlier project. Different optimization budgets and selected variants make this exploration, not a definitive ranking. The old 600-message study remains intact.','',
       'Even zero added errors in 100 independent examples would give an individual one-sided 95% upper error bound of about 2.95%, above the earlier 1% requirement. With 50 toxic examples, zero added toxic misses would give an upper bound of about 5.82%, above 5%. These reused samples offer still less basis for a confirmatory claim.','',
       'Next, carry promising development-selected recipes to genuinely unused messages with frozen thresholds, matched error limits and repeated isolated timing. Do not keep choosing variants against this 100-message set.','',
       '[Separate adversarial review](chat-smoke-review.md), [shared sample/protocol](../results/chat-smoke/protocol.json), [selection code](../experiments/chat_smoke_common.py). No raw chat text is published.']
    specialist_timing=ROOT/'results/chat-smoke-specialist/benchmark.json'
    if specialist_timing.exists():
        st=read(specialist_timing)
        lines+=['','## Specialist timing','',*table(['Path','Messages','Summed request seconds'],[[k,st['n'],f'{v:.2f}'] for k,v in st['total_seconds'].items()]),'',
            'One warm interleaved pass with rotating path order, four CPU threads and actual BERT plus Qwen execution for fallback requests. Includes original text preparation and readouts; excludes loading and training. These timings are not repeated-run estimates. The cascade newly misses one toxic message that its full-depth fallback gets right. [Every timed call](../results/chat-smoke-specialist/timings.json), [timing protocol](../results/chat-smoke-specialist/timing-protocol.json).']
    reset_path=ROOT/'results/chat-smoke-reset/joint.json'
    if reset_path.exists():
        reset=read(reset_path);rb=read('results/chat-smoke-reset/initial-frozen-baseline.json')
        lines+=['','## Separate shorter-warm-up repair','',
            'The adversarial review found that the original starting heads already fit almost every training label. A separately recorded repair reduces head warm-up from 200 to five optimizer steps, then repeats the joint adapter recipe. This was proposed after observing earlier failures; it is additional exploration, not a replacement for them.','',
            *table(['Layer','Initial correct /100','After training /100','Initial toxic misses /50','After training /50'],[[d,rb['metrics']['evaluation'][d]['correct'],m['correct'],rb['metrics']['evaluation'][d]['missed_toxic'],m['missed_toxic']] for d,m in reset['metrics']['evaluation'].items()]),'',
            '[Recorded rationale](../results/chat-smoke-reset/rationale.json), [protocol](../results/chat-smoke-reset/joint-protocol.json), [result](../results/chat-smoke-reset/joint.json), [matched initialization](../results/chat-smoke-reset/initial-frozen-baseline.json).']
    (ROOT/'docs/chat-smoke-results.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    details=['# Short Qwen adapter experiments','', 'These are exploratory reused-data results. Read the [combined comparison](chat-smoke-results.md) and [independent audit](chat-smoke-review.md) before interpreting the numbers.','',
       'Rank 4, scale 2 LoRA updates are attached to q/v projections in every retained block; original weights stay frozen. A task readout receives the last input position. Joint training averages human-label losses at 6/12/18/24. Distillation combines those losses with temperature 2 teacher KL loss. The fixed12 variant retains only the first 12 blocks and reads raw block 12 output, matching its initialization; full-24 readouts receive the final normalization.','',
       'Fresh forwards are used after weights change. The old hidden-state cache is used only to initialize the frozen starting heads. First-layer q/v adapter gradients are asserted nonzero; frozen base gradients stay absent. Every forward asserts contiguous execution through its retained blocks.','',
       'Initial heads use seed 73, 200 AdamW steps, train-only standardization and the common 384 labels. Adapter AdamW uses learning rate 0.0005, head rate 0.001, weight decay 0.01 and gradient clipping 1. The fixed 32-step budget covers 128 adapter message presentations from shuffled length buckets. Tune 32 selects step 16 or 32; development 64 and evaluation 100 do not select checkpoints.','']
    for v,r in a.items():
        details+=['## '+v,'',f'Selected step: {r["selected_step"]}. Retained decoder blocks: {r["retained_blocks"]}. Trainable adapter parameters: {r["trainable_adapter_parameters"]}.','',*table(['Readout layer','Correct /100','Toxic missed /50','Benign blocked /50'],[[d,m['correct'],m['missed_toxic'],m['false_block']] for d,m in r['metrics']['evaluation'].items()]),'',f'[Protocol](../results/chat-smoke-adaptation/{v}-protocol.json), [predictions and training history](../results/chat-smoke-adaptation/{v}.json), [portable weights](../results/chat-smoke-adaptation/{v}-weights.npz).','']
    details+=['The full-only adaptation loss does not train its intermediate heads after representation changes; their scores are diagnostic probes. Partial training, tiny development selection, one seed and a potentially weak teacher prevent conclusions about the limits of the methods. Concurrent training elapsed times are not speed measurements.','',
       '[Implementation used](../results/chat-smoke-adaptation/implementation.py), [budget amendment](../results/chat-smoke-adaptation/budget-amendment.json), [original interrupted protocol](../results/chat-smoke-adaptation/initial-full-protocol.json), [independently reconstructed initial baseline](../results/chat-smoke-adaptation/initial-frozen-baseline.json), [baseline reconstruction code](../experiments/chat_smoke_adaptation_baseline.py).','',
       'The root runner\'s optional timing path uses already tokenized input and computes all retained diagnostic readouts. It was not used for the comparison below. The separate runtime runner includes original text preparation and only the target head.','',
       'Prior methods: [LoRA](https://arxiv.org/abs/2106.09685), [FastBERT](https://arxiv.org/abs/2004.02178), [LayerSkip](https://arxiv.org/abs/2404.16710). These are small local adaptations of ideas, not reproductions of those papers\' training budgets or published results.']
    timings=[ROOT/f'results/chat-smoke-adaptation/{v}-runtime.json' for v in a]
    if all(p.exists() for p in timings):
        details+=['','## Actual target-head runtime replay','',*table(['Variant','Messages','Blocks','Summed request seconds','Prediction parity'],[[p.stem.replace('-runtime',''),r['n'],r['retained_blocks'],f'{r["seconds"]:.2f}',r['parity_passed']] for p in timings for r in [read(p)]]),'',
            'Each variant executes a separate warm pass on the same 50 IDs, using four CPU threads. The boundary includes original text preparation, actual transformer execution and only the target readout. Models were timed sequentially with no concurrent model jobs. These non-interleaved single passes establish runnable paths and prediction parity, not a replicated speed ranking. Their totals cannot be compared directly to the 100-message head/cascade totals.','',
            '[Timing protocol](../results/chat-smoke-adaptation/runtime-protocol.json), [runtime implementation](../experiments/chat_smoke_adaptation_runtime.py). Each variant runtime JSON records every duration and contiguous executed block trace.']
    (ROOT/'docs/chat-smoke-adaptation.md').write_text('\n'.join(details)+'\n',encoding='utf-8')
    print('Wrote completed exploratory comparison and adaptation report.')

if __name__=='__main__':main()
