"""Standalone small trained classifier demo, separate from pretrained Qwen output formats."""
def update(pages):
    pages['tiny-decision-demo.html']=dict(title='A small model, one decision',description='Try a trained moderation classifier on your device.',status='Live browser model',styles=['results.css'],scripts=['scripts/tiny-decision.js'],body='''
<p><a href="@/decisions.html">Back to decisions without text</a></p>
<p>This 4.4-million-parameter BERT model returns <strong>SAFE or BLOCK</strong> directly. It uses two layers and a two-output classifier. No reply tokens or vocabulary scores are generated.</p>
<p>The model download is <strong>17.5 MB</strong>, plus tokenizers and the browser runtime. It runs locally after loading. This is a different, trained model from the Qwen demo.</p>
<div class="actions"><button class="button" id="tiny-run">Run 100 real messages</button><button class="button secondary" id="tiny-stop" disabled>Stop</button><button class="button secondary" id="tiny-save" disabled>Save results</button></div>
<p id="tiny-status" role="status">Ready. Nothing has been downloaded.</p><label for="tiny-progress">Messages processed</label><progress id="tiny-progress" value="0" max="100" style="max-width:100%">0</progress>
<p id="tiny-summary"></p><p id="tiny-setup" class="small"></p>
<h2>Try a message</h2><label for="tiny-text">Message to classify</label><textarea id="tiny-text" rows="3" maxlength="10000" style="display:block;width:100%;max-width:100%;box-sizing:border-box">Hello, can you help me with my account?</textarea>
<div class="actions"><button class="button" id="tiny-classify">Classify locally</button></div><p id="tiny-output" role="status"></p>
<details><summary>How well does it work?</summary><p>The original Python model got 82 of these 100 real ToxicChat messages right: it missed 13 toxic messages and blocked 5 benign ones. The exported model preserved all 100 decisions. This is an exploratory, balanced sample already used in our research, not a production reliability estimate.</p><p>The browser checks tokenizer and decision agreement with that saved reference. Its total processing time includes tokenization, the same 256-Qwen-token input boundary, BERT execution and output reading. Model setup and dataset download are separate. Both BERT layers execute for every message.</p></details>
<details><summary>Data and model</summary><p>The base is Google BERT tiny, trained on 1,398 labeled ToxicChat messages; separate development data selected the model and threshold. The 100-message benchmark uses the saved refinement evaluation IDs, with 50 toxic and 50 benign messages. It is a different sample from the Qwen output-format demo, so their displayed totals are not a paired comparison.</p><p><a href="https://huggingface.co/datasets/lmsys/toxic-chat">ToxicChat</a> is CC BY-NC 4.0. The raw dataset is downloaded and checksum-checked. Saved browser reports contain IDs and predictions, not message text. Your typed message is processed locally and is not saved in the benchmark report.</p></details>
<p><a href="@/docs/decision-export.md">Export checks and limitations</a> · <a href="@/docs/chat-refinement.md">Training and previous results</a> · <a href="@/moderation-benchmark.html">Compare Qwen output formats</a></p>''')
