"""Two focused image-to-action pages; called by the shared site updater."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def read(p):return json.loads((ROOT/p).read_text(encoding='utf-8'))

def update(pages):
    screen=read('results/action-demo/screenstudy/result.json')['methods'];arrows=read('results/action-demo/arrows/result.json');test=arrows['summary']['test'];stress=arrows['summary']['outline_stress'];gate=screen['peak_gate']
    pages['screenshot-demo.html']={'title':'Where would it click?','description':'Replay a real screenshot and see the point the model chose.','status':'Recorded model outputs',
      'scripts':['scripts/action-demo-gallery.js'],'body':f'''<p><a href="@/coordinates.html">Back to finding where to click</a> · <a href="@/image-action-demo.html">Try a small live image model</a></p>
<p>These are <strong>saved GUI-Actor model outputs</strong> on 30 real ScreenSpot screenshots. No live vision model runs here. Choose a screenshot, read the task, and compare the point with the target.</p>
<style>.action-replay-stage{{position:relative;max-width:100%;margin:1rem 0}}.action-replay-stage img{{display:block;width:100%;height:auto;border:1px solid var(--line)}}#action-screen-point{{position:absolute;width:15px;height:15px;border:3px solid white;outline:2px solid #1743ae;background:#1743ae;border-radius:50%;transform:translate(-50%,-50%);pointer-events:none}}#action-screen-box{{position:absolute;border:3px dashed #087741;background:#08774120;pointer-events:none}}.action-replay-control{{display:flex;gap:1rem;flex-wrap:wrap;margin:1rem 0}}.action-replay-control label{{max-width:100%}}.action-replay-control select{{display:block;max-width:100%;min-height:44px}}#action-example{{width:100%}}</style>
<section class="paper"><label for="action-example">Recorded screenshot</label><select id="action-example" disabled></select>
<p style="margin-top:1rem"><strong>Task: <span id="action-instruction">Loading…</span></strong></p>
<div class="action-replay-control"><label for="action-readout">Choose the point<select id="action-readout" disabled><option value="connected_region">Combine nearby patches</option><option value="max_patch">Highest-scoring single patch</option></select></label><label><input type="checkbox" id="action-reveal"> Show the correct target</label></div>
<div class="action-replay-stage" id="action-screen-stage"><img id="action-screen-image" alt="Recorded screenshot"><span id="action-screen-box" hidden></span><span id="action-screen-point" aria-hidden="true"></span></div>
<p id="action-screen-status" role="status">Loading the recorded points…</p><div class="actions"><button class="button secondary" id="action-next">Next screenshot</button><a class="button secondary" id="action-screen-full" target="_blank" rel="noopener">Open full-size image</a></div><p id="action-screen-coordinates" class="small"></p>
<details><summary>Try the cautious review rule</summary><label><input type="checkbox" id="action-review"> Hold clicks below the tested cutoff</label><p id="action-review-detail"></p><p>On these 30 cases, this rule allowed {gate['accepted']} clicks: {gate['correct_clicks']} correct and {gate['wrong_clicks']} wrong. It sent {gate['review']} to review, including {gate['withheld_correct_points']} points that were already correct. Review is unresolved, not a successful click.</p></details></section>
<p>Combining nearby image patches hit <strong>25 / 30</strong> targets; using one patch hit <strong>16 / 30</strong>. Both used the same model pass. Every case ran all <strong>28 layers</strong> and generated <strong>zero text tokens</strong>.</p>
<p class="small"><a href="@/docs/action-demo.md">Methods, review-rule results and limits</a> · <a href="https://huggingface.co/datasets/bevaya/ScreenSpot">ScreenSpot dataset</a> · <a href="https://huggingface.co/microsoft/GUI-Actor-2B-Qwen2-VL">GUI-Actor model</a></p>'''}
    pages['image-action-demo.html']={'title':'Read an image. Return an action.','description':'A small trained model looks at the pixels and returns a direction.','status':'Live synthetic demo',
      'scripts':['scripts/action-demo-core.js','scripts/action-demo-live.js'],'body':f'''<p><a href="@/coordinates.html">Back to finding where to click</a> · <a href="@/screenshot-demo.html">Real screenshot recordings</a></p>
<p>This small trained model reads a 32×32 image and returns <strong>UP, RIGHT, DOWN or LEFT</strong>. It runs here in your browser. It learned synthetic arrow cards; it is not a general screenshot model.</p>
<style>.action-card-row{{display:flex;align-items:center;gap:2rem;flex-wrap:wrap}}#action-card{{width:160px;height:160px;image-rendering:pixelated;border:1px solid var(--line);background:white}}#action-live-result{{font-size:2rem;font-weight:650;margin:0}}.action-file-label input{{display:block;max-width:100%}}</style>
<section class="paper"><div class="action-card-row"><canvas id="action-card" width="32" height="32" role="img" aria-label="Arrow image to classify"></canvas><output id="action-live-result" aria-live="polite">Loading…</output></div>
<p id="action-live-status" role="status" style="margin-top:1rem">Loading a small set of trained weights. No large language model download.</p><div class="actions"><button class="button" id="action-new-card" disabled>New arrow</button></div>
<details><summary>Try your own arrow image</summary><p>Use a dark arrow on a light background. Your image stays in this browser. The model always chooses one of four directions, even for images outside its training.</p><label class="action-file-label">Arrow image<input type="file" id="action-upload" accept="image/png,image/jpeg,image/webp" disabled></label></details>
<details><summary>What actually runs?</summary><p>A neural network with <strong>32,932 trained parameters</strong> receives only the canvas pixels. A 32-unit hidden layer feeds four output scores. The highest score becomes the action. It does not receive the renderer's seed or answer, and it does not generate text.</p><p id="action-live-detail"></p><p><a href="@/results/action-demo/arrows/model.json">Trained weights</a> · <a href="@/scripts/action-demo-core.js">Renderer and inference code</a></p></details></section>
<h2>Try the same test</h2><p>On 400 new filled-arrow cards, the trained model got <strong>{test['neural_correct']} / 400</strong> correct; four fixed image templates got <strong>{test['template_correct']} / 400</strong>. An unseen outline style scored <strong>{stress['neural_correct']} / 400</strong> with the trained model. These are synthetic checks, not evidence of real-screen accuracy.</p>
<button class="button secondary" id="action-test" disabled>Run the 800-card check here</button><div id="action-test-output" role="status" style="margin-top:1rem"></div>
<p class="small"><a href="@/docs/action-demo.md">Training, controls and limitations</a> · <a href="@/results/action-demo/arrows/protocol.json">Sealed experiment</a> · <a href="@/results/action-demo/arrows/predictions.json">Every saved result</a></p>'''}
